"""Tests for Path 1/2 conservation (MAF parse + frame integrity)."""

from __future__ import annotations

from swissisoform.conservation_frame import (
    SpeciesFrameResult,
    aggregate_species_results,
    analyze_species,
    parse_maf,
)
from swissisoform.conservation_frame.maf import concat_species_rows

# ---------------------------------------------------------------------------
# MAF parser
# ---------------------------------------------------------------------------


_SAMPLE_MAF = """##maf version=1
# generated by hal2maf
a score=100.0
s hg38.chr1     1000 12 + 248956422 ATGAAAGGCTGA
s panTro6.chr1  1050 12 + 239755000 ATGAAAGGCTGA
s mm10.chr4     5000 12 + 195471971 ATGAAAGGGTGA

a score=50.0
s hg38.chr1     2000  6 + 248956422 GCTAAG
s panTro6.chr1  2050  6 + 239755000 GCTAAG
"""


class TestParseMaf:
    def test_block_count(self):
        assert len(parse_maf(_SAMPLE_MAF)) == 2

    def test_species_extracted(self):
        blocks = parse_maf(_SAMPLE_MAF)
        assert set(blocks[0].rows) == {"hg38", "panTro6", "mm10"}
        assert set(blocks[1].rows) == {"hg38", "panTro6"}

    def test_row_fields(self):
        blocks = parse_maf(_SAMPLE_MAF)
        row = blocks[0].rows["hg38"]
        assert row.start == 1000
        assert row.size == 12
        assert row.strand == "+"
        assert row.seq == "ATGAAAGGCTGA"

    def test_skips_junk_lines(self):
        maf = "# header\n\ni not-an-s-line\na\ns hg38.chr1 0 3 + 100 ATG\n"
        blocks = parse_maf(maf)
        assert len(blocks) == 1
        assert blocks[0].rows["hg38"].seq == "ATG"


class TestConcatSpeciesRows:
    def test_concat_across_blocks(self):
        blocks = parse_maf(_SAMPLE_MAF)
        out = concat_species_rows(blocks, "panTro6", "hg38")
        assert out is not None
        ref, sp = out
        assert ref == "ATGAAAGGCTGA" + "GCTAAG"
        assert sp == "ATGAAAGGCTGA" + "GCTAAG"

    def test_missing_species_padded(self):
        blocks = parse_maf(_SAMPLE_MAF)
        out = concat_species_rows(blocks, "mm10", "hg38")
        assert out is not None
        ref, sp = out
        # mm10 present in block 1 only; block 2 pads with gaps
        assert ref == "ATGAAAGGCTGA" + "GCTAAG"
        assert sp == "ATGAAAGGGTGA" + "------"

    def test_missing_reference_returns_none(self):
        blocks = parse_maf("a\ns mm10.chr4 0 3 + 100 ATG\n")
        assert concat_species_rows(blocks, "mm10", "hg38") is None


# ---------------------------------------------------------------------------
# analyze_species
# ---------------------------------------------------------------------------


class TestAnalyzeSpecies:
    def test_identical_sequences(self):
        ref = "ATGAAATAA"
        # stop is the last ref codon → not "premature"
        res = analyze_species("foo", ref, ref)
        assert res.aligned is True
        assert res.start_codon_conserved is True
        assert res.frame_intact is True
        assert res.premature_stop is False
        assert res.n_frameshifts == 0
        assert res.pident == 1.0

    def test_in_frame_substitution(self):
        ref = "ATGAAACCC"
        tgt = "ATGAAACCT"  # silent-at-nt, P at AA3
        res = analyze_species("foo", ref, tgt)
        assert res.frame_intact is True
        assert res.start_codon_conserved is True
        assert res.pident == 1.0  # both still translate to MKP

    def test_premature_stop_detected(self):
        # ref = MKP (ATG AAA CCC); target swaps middle codon to TAA (stop)
        ref = "ATGAAACCC"
        tgt = "ATGTAACCC"
        res = analyze_species("foo", ref, tgt)
        assert res.premature_stop is True
        assert res.frame_intact is False

    def test_start_codon_lost(self):
        ref = "ATGAAACCC"
        tgt = "CTGAAACCC"  # leucine start
        res = analyze_species("foo", ref, tgt)
        assert res.start_codon_conserved is False
        assert res.start_codon == "CTG"

    def test_frameshift_deletion(self):
        # Single-base deletion in target → frameshift
        ref = "ATGAAACCCGGGTAA"
        tgt = "ATGAA-CCCGGGTAA"
        res = analyze_species("foo", ref, tgt)
        assert res.n_frameshifts == 1
        assert res.frame_intact is False

    def test_in_frame_deletion_ok(self):
        # 3-base deletion preserves frame
        ref = "ATGAAACCCGGGTAA"
        tgt = "ATG---CCCGGGTAA"
        res = analyze_species("foo", ref, tgt)
        assert res.n_frameshifts == 0
        assert res.frame_intact is True

    def test_unaligned_when_all_gaps(self):
        ref = "ATGAAA"
        tgt = "------"
        res = analyze_species("foo", ref, tgt)
        assert res.aligned is False
        assert res.frame_intact is None

    def test_unequal_lengths_raise(self):
        import pytest

        with pytest.raises(ValueError):
            analyze_species("foo", "ATG", "ATGAAA")


# ---------------------------------------------------------------------------
# Aggregation
# ---------------------------------------------------------------------------


class TestAggregate:
    def test_no_aligned_species(self):
        out = aggregate_species_results(
            [SpeciesFrameResult(species="x", aligned=False, coverage=0.0)]
        )
        assert out["n_species_aligned"] == 0
        assert out["frac_intact"] is None

    def test_mixed_results(self):
        results = [
            SpeciesFrameResult(
                species="a", aligned=True, frame_intact=True,
                start_codon_conserved=True, pident=1.0,
            ),
            SpeciesFrameResult(
                species="b", aligned=True, frame_intact=False,
                start_codon_conserved=True, pident=0.5,
            ),
            SpeciesFrameResult(species="c", aligned=False),
        ]
        out = aggregate_species_results(results)
        assert out["n_species_aligned"] == 2
        assert out["n_species_intact_frame"] == 1
        assert out["frac_intact"] == 0.5
        assert out["start_codon_conserved"] == 1.0
        assert out["mean_pident"] == 0.75
